import vue from '@vitejs/plugin-vue'
import fs from 'fs'
import path from 'path'
import compression from 'compression'
import type { Plugin } from 'vite'
import { defineConfig } from 'vite'
import viteCompression from 'vite-plugin-compression2'
import {
  authorizeAdminProxyRequest,
  isProtectedApiMutation,
  resolveAdminProxyTrust,
} from './src/admin-proxy-trust'

// Dev server gzip compression plugin
function devCompressionPlugin(): Plugin {
  return {
    name: 'dev-compression',
    configureServer(server) {
      server.middlewares.use(compression({ threshold: 1 }))
    },
  }
}

function httpsConfig(): false | { key: Buffer; cert: Buffer } {
  if (process.env.HOMERAIL_UI_HTTPS !== '1') return false
  const keyPath = process.env.HOMERAIL_UI_HTTPS_KEY
  const certPath = process.env.HOMERAIL_UI_HTTPS_CERT
  if (!keyPath || !certPath) {
    throw new Error('HOMERAIL_UI_HTTPS_KEY and HOMERAIL_UI_HTTPS_CERT are required when HOMERAIL_UI_HTTPS=1')
  }
  return {
    key: fs.readFileSync(keyPath),
    cert: fs.readFileSync(certPath),
  }
}

const managerPort = process.env.VITE_HOMERAIL_MANAGER_PORT || '19191'
const managerHttpTarget = process.env.HOMERAIL_MANAGER_HTTP || process.env.VITE_API_BASE_URL || process.env.VITE_API_URL || `http://localhost:${managerPort}`
const managerWsTarget = (
  process.env.VITE_WS_URL
  || managerHttpTarget.replace(/^http:/, 'ws:').replace(/^https:/, 'wss:')
)
const managerAdminToken = process.env.HOMERAIL_MANAGER_ADMIN_TOKEN || ''
const adminProxyTrust = resolveAdminProxyTrust({
  enabled: process.env.HOMERAIL_UI_ADMIN_PROXY_ENABLED === '1',
  uiOrigin: process.env.HOMERAIL_UI_ORIGIN || '',
  uiBindHost: process.env.HOMERAIL_UI_HOST || '',
  managerUrl: managerHttpTarget,
  unsafeAllowPublicNoAuth: process.env.HOMERAIL_UNSAFE_ALLOW_PUBLIC_MANAGER_WITHOUT_AUTH === '1',
})

function adminProxyGuardPlugin(): Plugin {
  return {
    name: 'homerail-admin-proxy-guard',
    enforce: 'pre',
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        if (!isProtectedApiMutation(req.method, req.url)) return next()
        const authorization = authorizeAdminProxyRequest(
          adminProxyTrust,
          req.headers.origin,
          req.headers['sec-fetch-site'],
        )
        if (authorization.allowed) return next()
        req.resume()
        res.writeHead(403, {
          'content-type': 'application/json',
          'cache-control': 'no-store',
        })
        res.end(JSON.stringify({ success: false, error: authorization.reason }))
      })
    },
  }
}

function configureManagerProxy(proxy: { on: (event: string, listener: (...args: any[]) => void) => void }): void {
  proxy.on('proxyReq', (proxyReq: { removeHeader: (name: string) => void; setHeader: (name: string, value: string) => void }, req: { method?: string; url?: string; headers: Record<string, string | string[] | undefined> }) => {
    if (!isProtectedApiMutation(req.method, req.url)) return
    proxyReq.removeHeader('authorization')
    const authorization = authorizeAdminProxyRequest(
      adminProxyTrust,
      req.headers.origin,
      req.headers['sec-fetch-site'],
    )
    if (authorization.allowed && managerAdminToken) {
      proxyReq.setHeader('authorization', `Bearer ${managerAdminToken}`)
    }
  })
}

// NOTE: For production nginx, uncomment `gzip on;` in /usr/trim/nginx/conf/nginx.conf
// and add gzip_static on; to serve pre-compressed .gz files generated by viteCompression plugin.

export default defineConfig({
  base: './',
  plugins: [
    vue(),
    viteCompression({
      algorithms: [{
        type: 'gzip',
        algorithm: 'gzip',
      }],
      threshold: 1024,
    }),
    adminProxyGuardPlugin(),
    devCompressionPlugin(),
  ],
  css: {
    postcss: './postcss.config.js',
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src')
    },
    extensions: ['.mjs', '.js', '.ts', '.json', '.vue']
  },
  build: {
    target: 'esnext',
    sourcemap: process.env.NODE_ENV === 'development',
    chunkSizeWarningLimit: 1000
  },
  optimizeDeps: {
    include: ['vue']
  },
  server: {
    port: Number(process.env.HOMERAIL_UI_PORT || process.env.VITE_HOMERAIL_UI_PORT || 19192),
    host: true,
    https: httpsConfig(),
    hmr: {
      overlay: true
    },
    proxy: {
      '/api': {
        target: managerHttpTarget,
        ws: true,
        changeOrigin: true,
        secure: false,
        rewrite: (path) => path,
        configure: configureManagerProxy,
      },
      '/artifacts': {
        target: managerHttpTarget,
        changeOrigin: true,
        secure: false,
        rewrite: (path) => path
      },
      '/ws': {
        target: managerWsTarget,
        ws: true,
        changeOrigin: true,
        secure: false
      }
    }
  }
})
